---
- hosts: all
  connection: local
  gather_facts: no
  tasks:
    - name: Install WireGuard
      package:
        name: wireguard
        state: present

    - name: Enable IPv4 forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes

    - name: Enable IPv6 forwarding
      sysctl:
        name: net.ipv6.conf.all.forwarding
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes

    - name: Configure nftables rules
      copy:
        src: ./nftables.conf
        dest: /etc/nftables.conf

    - name: Enable and start nftables
      systemd:
        name: nftables
        enabled: yes
        state: started