---
- hosts: all
#  connection: local
  gather_facts: no
  tasks:
    - name: Install packages
      ansible.builtin.package:
        name:
          - postfix
          - dovecot-core
          - dovecot-ldap
          - dovecot-sieve
          - dovecot-managesieved
          - postfix
          - postfix-ldap
        state: present

#    - name: Copy nginx.conf
#      ansible.builtin.copy:
#        src: ./nginx.conf
#        dest: /etc/nginx/nginx.conf
#    - name: fetch the hostname
#      command: hostname
#      register: host_output
#    - name: inject the hostname into the nginx.conf
#      replace:
#        path: /etc/nginx/nginx.conf
#        regexp: 'snakeoil'   # Specify the string/regex to find in the file
#        replace: "{{ host_output.stdout }}"
#
#    - name: Restart + enable nginx on boot
#      ansible.builtin.systemd_service:
#        state: restarted
#        name: nginx
#        enabled: true