---
- hosts: all
  connection: local
  gather_facts: no
  tasks:
    - name: Gather the system facts
      ansible.builtin.setup:

    - name: Install packages
      ansible.builtin.package:
        name:
          - postfix
          - dovecot-core
          - dovecot-ldap
          - dovecot-sieve
          - dovecot-imapd
        state: present

    - name: Copy postfix config
      ansible.builtin.copy:
        src: ./postfix/
        dest: /etc/postfix
        force: yes
    - name: Copy dovecot config
      ansible.builtin.copy:
        src: ./dovecot/
        dest: /etc/dovecot
        force: yes
    - name: Copy backup script
      ansible.builtin.copy:
        src: ./backup.sh
        dest: /opt
        force: yes
    - name: Copy postfix cert
      ansible.builtin.copy:
        src: ./postfix/postfix.pem
        dest: /etc/ssl/certs
        force: yes
    - name: Copy postfix key
      ansible.builtin.copy:
        src: ./postfix/postfix.key
        dest: /etc/ssl/private
        force: yes
    - name: Copy ssh ca files
      ansible.builtin.copy:
        src: ./ssh/
        dest: /etc/ssh
        force: yes
    - name: Add CA to sshd_conf
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        line: TrustedUserCAKeys /etc/ssh/ca.key.pub
        create: yes

    - name: Ensure vmail group exists
      group:
        name: vmail
        state: present
    - name: Add vmail user for Dovecot
      user:
        name: vmail
        comment: "Virtual Mail User"
        group: vmail

    - name: Create directory /var/mailboxes
      ansible.builtin.file:
        path: /var/mailboxes
        state: directory
        mode: '0700'
        owner: vmail
        group: vmail

    - name: Create a partition on /dev/sdb
      parted:
        device: /dev/sdb
        number: 1
        state: present
        part_type: primary
        fs_type: ext4
        resize: yes

    - name: Create filesystem
      community.general.filesystem:
        fstype: ext4
        dev: /dev/sdb1
        state: present

    - name: Get UUID of filesystem
      ansible.builtin.command: lsblk /dev/sdb1 -no UUID -I 8 -d
      register: fs_UUID

    - name: Fail if UUID is not an UUID
      ansible.builtin.fail:
        msg: Could not evaluate the fs UUID!
      when: fs_UUID.stdout is not regex('^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$')

    - name: Mount filesystem
      ansible.posix.mount:
        path: "/opt/backup"
        src: "UUID={{ fs_UUID.stdout }}"
        fstype: ext4
        state: mounted

    - name: Restart + enable postfix on boot
      ansible.builtin.systemd_service:
        state: restarted
        name: postfix
        enabled: true
        
    - name: Restart + enable dovecot on boot
      ansible.builtin.systemd_service:
        state: restarted
        name: dovecot
        enabled: true