---
- hosts: all
  gather_facts: no
  tasks:
  - name: Install nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: Copy nginx.conf
    ansible.builtin.copy:
      src: ./nginx.conf
      dest: /etc/nginx/nginx.conf
  - name: fetch the hostname
    command: hostname
    register: host_output
  - name: inject the hostname into the nginx.conf
    replace:
      path: /etc/nginx/nginx.conf
      regexp: 'snakeoil'   # Specify the string/regex to find in the file
      replace: "{{ host_output.stdout }}"

  - name: Restart + enable nginx on boot
    ansible.builtin.systemd_service:
      state: restarted
      name: nginx
      enabled: true