---
- hosts: all
  connection: local
  gather_facts: no
  tasks:
    - name: Install gnome
      ansible.builtin.package:
        name:
          - gnome
          - thunderbird
          - wireguard
        state: present
